<?php
/**
 * @file
 * Helps site builders and module developers investigate a site.
 */

/**
 * Implements hook_preprocess_views_view().
 *
 * Add collection term as view header.
 */
function bb_sync_translation_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->name == 'collection_products') {
    if ($view->current_display == 'page') {
      // Keep the previous theming.
//      $vars['classes_array'][] = 'view-collection-taxonomy-term';
      $tid = $view->args['0'];
      $term = i18n_taxonomy_localize_terms(taxonomy_term_load($tid));
      $vars['collection_title'] = i18n_string_translate('taxonomy:term:'.$tid.':name',$term->name);    
//      dpm(i18n_taxonomy_localize_terms($term));
//      $vars['collection_image_url'] = NULL;
//      if (!empty($term->field_image) && !empty($term->field_image[LANGUAGE_NONE][0]['uri'])) {
//        $vars['collection_image_url'] = file_create_url($term->field_image[LANGUAGE_NONE][0]['uri']);
//      }
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Change the order the hooks are executed.
 */
function bb_sync_translation_module_implements_alter(&$implementations, $hook) {
//  debug("1- ".$hook);
//  if ($hook == 'block_view_alter') {dpm($hook);}
//  if ($hook == 'preprocess_views_view') {
//    debug("2");
//    // Move my_module_rdf_mapping() to the end of the list. module_implements()
//    // iterates through $implementations with a foreach loop which PHP iterates
//    // in the order that the items were added, so to move an item to the end of
//    // the array, we remove it and then add it.
//    $group = $implementations['bb_sync_translation'];
//    unset($implementations['bb_sync_translation']);
//    $implementations['bb_sync_translation'] = $group;
//  }
}